# Generated by Django 4.0.4 on 2022-05-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=10)),
                ('price_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_author', models.CharField(max_length=50)),
                ('date_posted', models.DateField()),
                ('time_to_cook', models.DurationField()),
                ('description_of_meal', models.CharField(max_length=250)),
                ('meal_instructions', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredientJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.ingredient')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CookRecipeJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.recipe')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.user')),
            ],
        ),
    ]
